language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install: pip install -r requirements.txt --use-mirrors
script: 
  - ln -s gsmmodem test/gsmmodem
  - ln -s tools/gsmtermlib test/gsmtermlib
  - python test/runalltests.py
