language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install:
  # Install unittest2 on Python 2.6
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - pip install -r requirements.txt --use-mirrors
script: if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then unit2 discover; else python -m unittest discover; fi
